markdown: kramdown
highlighter: rouge
permalink: /posts/:title
auto: true
title : Kappy Space by Joao Matos Silva
production_url : http://kappy.github.io
description: "Personal Blog about software architecture and life"
disqus_shortname: kappyspace
analytics: UA-42239910-1
gauges: a
author :
  name : Joao Matos Silva
  github : joaomatossilva
  twitter : kappyzor
  facebookAppId: 779368612088019
  email: joao@kspace.pt
prose:
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "text"
          label: "Layout"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
